parameters:
- name: design_stage
  type: object
- name: build_stage
  type: object
- name: target_stages
  type: object
- name: all_stages
  type: object
- name: build_environments_mapping
  type: object
- name: build_job_assignment_mechanism
  type: string
- name: environment_set
  type: string
- name: deployment_sets
  type: object

stages:
- ${{ each target_stage in parameters.target_stages }}:
  - ${{ each deployment_set in parameters.deployment_sets }}:
    - ${{ each deployment_target in deployment_set.targets }}:
      - ${{ if eq(target_stage.name, deployment_target) }}:
        - ${{ each api_project in deployment_set.api_projects }}:
          - stage: Build_${{api_project}}_and_deploy_it_on_${{deployment_target}}
            dependsOn: []
            lockBehavior: sequential
            jobs:
            - template: /pipelines/job-templates/build-api-using-${{parameters.build_job_assignment_mechanism}}.yml
              parameters:
                environment_set: ${{parameters.environment_set}}
                build_stage: ${{parameters.build_stage}}
                target_stage: ${{target_stage}}
                api_project: ${{api_project}}
                deployment_target: ${{deployment_target}}
                build_environments_mapping: ${{parameters.build_environments_mapping}}

            - ${{ each deploy_environment in target_stage.environments }}:
              - deployment: 'Deploy_${{api_project}}_to_API_Gateway_${{deploy_environment.name}}'
                dependsOn: 'Build_${{api_project}}_for_API_Gateway_${{deployment_target}}'
                environment: API_Gateway_${{parameters.environment_set}}_${{deploy_environment.name}}
                variables:
                - group: API_Gateway_${{parameters.environment_set}}_users
                - group: API_Gateway_${{parameters.environment_set}}_${{target_stage.name}}_users
                - group: API_Gateway_${{parameters.environment_set}}_${{deploy_environment.name}}_users
                pool:
                  name: ${{deploy_environment.pool_name}}
                  vmImage: ${{deploy_environment.pool_image}}
                strategy:
                  runOnce:    #rolling, canary are the other strategies that are supported
                    deploy:
                      steps:
                      - checkout: self
                        submodules: "true"
                        persistCredentials: "true"
                        fetchDepth: 0
                      - template: /pipelines/step-templates/retrieve-build.yml
                        parameters:
                          target_stage_name: ${{deployment_target}}
                          api_project: ${{api_project}}
                      - template: /pipelines/step-templates/deploy-api.yml
                        parameters:
                          environment_set: ${{parameters.environment_set}}
                          api_project: ${{api_project}}
                          target_environment_file: API_Gateway_${{deploy_environment.name}}_environment.json
                          target_stage_name: ${{deployment_target}}

                      - bash: |
                          echo "##vso[build.addbuildtag]${{parameters.environment_set}}"
                          echo "##vso[build.addbuildtag]${{deployment_target}}"
                          echo "##vso[build.addbuildtag]${{deploy_environment.name}}"
                          echo "##vso[build.addbuildtag]${{api_project}}"
                          echo "##vso[build.addbuildtag]${{api_project}}_${{deployment_target}}"
                          echo "##vso[build.addbuildtag]${{api_project}}_${{deploy_environment.name}}"
                        displayName: Add build tags