parameters:
- name: environment_set
- name: stage_name
- name: environment_name
- name: environment_file

steps:
- bash: |
    echo "##vso[task.setvariable variable=environment_insecure_flag]`jq -r '.values[] | select(.key == "insecure_flag") | .value' environments/${{parameters.environment_set}}/${{parameters.environment_file}}`"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Read and parse API Gateway ${{parameters.environment_name}} configuration, extract insecure_flag'

- bash: |
    newman run postman/collections/utilities/haft/Validate_HAFT_on_${{parameters.environment_name}}.json --reporters cli \
    --env-var haft_manager_user='$(haft_manager_user)' \
    --env-var haft_manager_password='$(haft_manager_password)' \
    -e environments/${{parameters.environment_set}}/${{parameters.environment_file}} \
    $(environment_insecure_flag)
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Validate High Availability and Fault Tolerance for API Gateway ${{parameters.environment_name}}'