parameters:
- name: environment_set
- name: stage_name
- name: environment_name
- name: environment_file

steps:
- bash: |
    echo "##vso[task.setvariable variable=environment_insecure_flag]`jq -r '.values[] | select(.key == "insecure_flag") | .value' environments/${{parameters.environment_set}}/${{parameters.environment_file}}`"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Read and parse API Gateway ${{parameters.environment_name}} configuration, extract insecure_flag'

- bash: |
    cat environments/${{parameters.environment_set}}/API_Gateway_${{parameters.stage_name}}_haft_globals.json
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Debug global variables file'

- bash: |
    newman run postman/collections/utilities/haft/Configure_HAFT_ring_on_${{parameters.environment_name}}.json --reporters cli \
    --env-var haft_manager_user='$(haft_manager_user)' \
    --env-var haft_manager_password='$(haft_manager_password)' \
    -e environments/${{parameters.environment_set}}/${{parameters.environment_file}} \
    -g environments/${{parameters.environment_set}}/API_Gateway_${{parameters.stage_name}}_haft_globals.json \
    --global-var nodeName_01=$(node_name_01) \
    --global-var nodeName_02=$(node_name_02) \
    $(environment_insecure_flag)
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Initialize High Availability and Fault Tolerance (HAFT) ring for API Gateway ${{parameters.environment_name}}'