parameters:
- name: environment_set
- name: stage_name
- name: environment_name
- name: environment_file

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/configuration/${{parameters.stage_name}}/assets'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId)_${{parameters.stage_name}}_configuration.zip'
    replaceExistingArchive: true
    verbose: true
  displayName: 'Create the API deployable from the flat representation for API Gateway ${{parameters.stage_name}} configuration'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/$(Build.BuildId)_${{parameters.stage_name}}_configuration.zip'
    artifactName: '${{parameters.stage_name}}_import'
  displayName: 'Publish the API deployable to pipeline build'

- bash: |
   echo "##vso[task.setvariable variable=environment_hostname]`jq -r '.values[] | select(.key == "hostname") | .value' environments/${{parameters.environment_set}}/${{parameters.environment_file}}`"
   echo "##vso[task.setvariable variable=environment_ip]`jq -r '.values[] | select(.key == "ip") | .value' environments/${{parameters.environment_set}}/${{parameters.environment_file}}`"
   echo "##vso[task.setvariable variable=environment_port]`jq -r '.values[] | select(.key == "port") | .value' environments/${{parameters.environment_set}}/${{parameters.environment_file}}`"
   echo "##vso[task.setvariable variable=environment_insecure_flag]`jq -r '.values[] | select(.key == "insecure_flag") | .value' environments/${{parameters.environment_set}}/${{parameters.environment_file}}`"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Read and parse API Gateway ${{parameters.environment_name}} configuration, extract ip, hostname, port and insecure_flag'

- bash: |
    echo "##vso[task.setvariable variable=scopes]`jq -c '.' $(System.DefaultWorkingDirectory)/configuration/${{parameters.stage_name}}/scopes.json`"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Prepare list of scopes to be imported'

- bash: |
    newman run postman/collections/utilities/import/Import_API_Gateway_config.json --reporters cli \
    --env-var importer_user='$(importer_user)' \
    --env-var importer_password='$(importer_password)' \
    --env-var initializer_user='$(initializer_user)' \
    --env-var initializer_password='$(initializer_password)' \
    --env-var scopes='$(scopes)' \
    --env-var file_Loc=$(System.DefaultWorkingDirectory)/$(Build.BuildId)_${{parameters.stage_name}}_configuration.zip \
    -e $(System.DefaultWorkingDirectory)/environments/${{parameters.environment_set}}/${{parameters.environment_file}} \
    $(environment_insecure_flag)
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Import the deployable to API Gateway ${{parameters.environment_name}}'
  env:
    no_proxy: $(environment_ip)

- bash: |
    newman run postman/collections/utilities/initialize/Initialize_${{parameters.stage_name}}.json --reporters cli \
    --env-var initializer_user='$(initializer_user)' \
    --env-var initializer_password='$(initializer_password)' \
    --env-var elasticsearch_user='$(apigw_analytics_user)' \
    --env-var elasticsearch_password='$(apigw_analytics_password)' \
    -e $(System.DefaultWorkingDirectory)/environments/${{parameters.environment_set}}/${{parameters.environment_file}} \
    $(environment_insecure_flag)
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Initialize API Gateway ${{parameters.environment_name}}'
  env:
    no_proxy: $(environment_ip)