# Pipeline for apig staging

trigger: none

# To do: Add target_type as pipeline parameter (vs. pipeline variable)
# parameters:
# - name: target_type
#   type: string
#   default: 'DEV-INT'

variables:
  ${{ if startsWith(variables['Build.DefinitionName'], 'wm_test_apigw_staging') }}:
    tenant: playground
  ${{ if startsWith(variables['Build.DefinitionName'], 'wm_apigw_staging') }}:
    tenant: realworld
  ${{ if endsWith(variables['Build.DefinitionName'], 'config') }}:
    targetType: CONFIG
  ${{ if endsWith(variables['Build.DefinitionName'], 'build') }}:
    targetType: BUILD
  ${{ if endsWith(variables['Build.DefinitionName'], 'dev_int') }}:
    targetType: DEV-INT
  ${{ if endsWith(variables['Build.DefinitionName'], 'dev_ext') }}:
    targetType: DEV-EXT
  ${{ if endsWith(variables['Build.DefinitionName'], 'stage_int') }}:
    targetType: STAGE-INT
  ${{ if endsWith(variables['Build.DefinitionName'], 'stage_ext') }}:
    targetType: STAGE-EXT
  ${{ if endsWith(variables['Build.DefinitionName'], 'prod_int') }}:
    targetType: PROD-INT
  ${{ if endsWith(variables['Build.DefinitionName'], 'prod_ext') }}:
    targetType: PROD-EXT

jobs:
- job: Configure_API_Gateway
  variables:
  - template: /${{variables.tenant}}/variables/${{variables.targetType}}/variables-template.yml
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - template: /pipelines/api-configure-template.yml  # Template reference
    parameters:
      environment: $(environment)
      type: $(targetType)
      tenant: $(tenant)