trigger: none

parameters:
- name: selected_api_project
  displayName: Export which API project?
  type: string
  values:
  - petstore
  - petstore_basicauth
  - petstore_versioning
  - postman_echo
  - postman_echo_mocking
  - postman_echo_multiple_tenants
  - postman_echo_oauth2
  - postman_echo_jwt
  - postman_echo_security_alias
  - ping
  - number_conversion
  - odata_tutorial
  - countries
  - cross_stage_app
  - only_test_int
  - only_test_ext
- name: selected_environment_set
  displayName: Export API(s) from DESIGN API Gateway in which environment set?
  default: webm_io
  values:
  - webm_io
  - azure_demo_01
- name: commit_message
  displayName: Message for the commit in Git?
  type: string

name: "$(Date:yyyyMMdd).$(Rev:r)-${{parameters.selected_api_project}}"

stages:
- template: /pipelines/stage-templates/inject-parameters-for-${{parameters.selected_environment_set}}.yml
  parameters:
    template: /pipelines/stage-templates/export-api.yml
    parameters:
      commit_message: ${{parameters.commit_message}}
      selected_api_project: ${{parameters.selected_api_project}}
    selected_environment_set: ${{parameters.selected_environment_set}}